groups:
- name: disk
  rules:
  - alert: DiskUsageHigh
    expr: (1 - node_filesystem_avail_bytes{fstype!~"tmpfs|overlay|aufs",mountpoint!~"/(run|boot|var/lib/docker).*"}
               / node_filesystem_size_bytes{fstype!~"tmpfs|overlay|aufs",mountpoint!~"/(run|boot|var/lib/docker).*"}) * 100 > 80
    for: 5m
    labels: { severity: "warning" }
    annotations:
      summary: "Disk >80% on {{ $labels.instance }} ({{ $labels.mountpoint }})"

  - alert: DiskUsageCritical
    expr: (1 - node_filesystem_avail_bytes{fstype!~"tmpfs|overlay|aufs",mountpoint!~"/(run|boot|var/lib/docker).*"}
               / node_filesystem_size_bytes{fstype!~"tmpfs|overlay|aufs",mountpoint!~"/(run|boot|var/lib/docker).*"}) * 100 > 90
    for: 2m
    labels: { severity: "critical" }
    annotations:
      summary: "Disk >90% on {{ $labels.instance }} ({{ $labels.mountpoint }})"

- name: kafka
  rules:
  - alert: KafkaConsumerLagHigh
    expr: kafka_consumergroup_lag > 5000
    for: 2m
    labels: { severity: "warning" }
    annotations:
      summary: "Kafka lag high ({{ $labels.consumergroup }} on {{ $labels.topic }})"

  - alert: KafkaConsumerLagTotalHigh
    expr: sum by (consumergroup, topic) (kafka_consumergroup_lag) > 20000
    for: 2m
    labels: { severity: "critical" }
    annotations:
      summary: "Kafka TOTAL lag high ({{ $labels.consumergroup }} on {{ $labels.topic }})"

