#!/usr/bin/env bash
set -euo pipefail
ROLE="${1:-}"; [[ -z "$ROLE" ]] && { echo "usage: $0 <server1|server2|server3>"; exit 1; }

BASE="envs/dev.env"
OVR="envs/${ROLE}/dev.env"
DST="/etc/sharpe10/dev.env"

mkdir -p /etc/sharpe10

{
  echo "# Generated by seed_env.sh on $(date)"
  echo "ROLE=${ROLE}"
  echo

  if [[ -f "$BASE" ]]; then
    echo "# ---- Global defaults: envs/dev.env ----"
    cat "$BASE"
    echo
  fi

  if [[ -f "$OVR" ]]; then
    echo "# ---- Role overrides: envs/${ROLE}/dev.env ----"
    cat "$OVR"
    echo
  fi
} > "$DST"

echo "[env] wrote $DST (ROLE=$ROLE)"
