name: repo-health
on: [push, pull_request]
jobs:
  smoke-matrix:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        role: [server1, server2, server3]
    steps:
      - uses: actions/checkout@v4
      - name: Show make targets
        run: make help || true
      - name: Smoke (mock mode)
        env:
          ENV_NAME: dev
          ROLE: ${{ matrix.role }}
          SMOKE_MODE: mock
        run: make smoke ENV_NAME=$ENV_NAME ROLE=$ROLE SMOKE_MODE=$SMOKE_MODE
